#!/bin/bash

echo "Running all CI checks..."
make ci

if [ $? -ne 0 ]; then
    echo -e "\033[31mError: CI checks failed. Please fix the errors above.\033[0m"
    echo -e "\033[33mTip: Run 'make ci' to run all checks locally.\033[0m"
    exit 1
fi

echo -e "\033[32mAll CI checks passed!\033[0m"
exit 0
